-- 코드를 입력하세요
# 식당 정보: REST_INFO
# 음식 종류별로 즐겨찾기가 가장 많은 식당 정보 출력
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (
    SELECT MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE
)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;