# 가게 상반기 주문 정보: FIRST_HALF
# 7월 주분 정보: JULY
# 7월 총 주문량과 상반기 총 주문량 합이 큰 순서대로 3개
SELECT F.FLAVOR FROM FIRST_HALF F JOIN JULY J
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC LIMIT 3;