-- 코드를 입력하세요
# 판매중인 도서 정보: BOOK
# 2021년 출판된 카테고리 인문에 속하는 
SELECT BOOK_ID, 
DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE FROM BOOK
WHERE CATEGORY = '인문'
AND DATE_FORMAT(PUBLISHED_DATE, '%Y') = '2021'
ORDER BY PUBLISHED_DATE ASC;